//////////////////////////////////////////////////////////////////////////////
//
// (C) Copyright Ion Gaztanaga 2014-2014. Distributed under the Boost
// Software License, Version 1.0. (See accompanying file
// LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
// See http://www.boost.org/libs/container for documentation.
//
//////////////////////////////////////////////////////////////////////////////

#ifndef BHO_MOVE_DETAIL_FWD_MACROS_HPP
#define BHO_MOVE_DETAIL_FWD_MACROS_HPP

#ifndef BHO_CONFIG_HPP
#  include <asio2/bho/config.hpp>
#endif
#
#if defined(BHO_HAS_PRAGMA_ONCE)
#  pragma once
#endif

#include <asio2/bho/move/detail/workaround.hpp>

namespace bho {
namespace move_detail {

template <typename T> struct unvoid { typedef T type; };
template <> struct unvoid<void> { struct type { }; };
template <> struct unvoid<const void> { struct type { }; };

}  //namespace move_detail {
}  //namespace bho {

#if !defined(BHO_NO_CXX11_RVALUE_REFERENCES)

#if defined(BHO_MOVE_MSVC_10_MEMBER_RVALUE_REF_BUG)

namespace bho {
namespace move_detail {

   template<class T>
   struct mref;

   template<class T>
   struct mref<T &>
   {
      explicit mref(T &t) : t_(t){}
      T &t_;
      T & get() {  return t_;   }
   };

   template<class T>
   struct mref
   {
      explicit mref(T &&t) : t_(t) {}
      T &t_;
      T &&get() {  return ::bho::move(t_);   }
   };

}  //namespace move_detail {
}  //namespace bho {

#endif   //BHO_MOVE_MSVC_10_MEMBER_RVALUE_REF_BUG
#endif   //!defined(BHO_NO_CXX11_RVALUE_REFERENCES)

//BHO_MOVE_REPEATN(MACRO)
#define BHO_MOVE_REPEAT(x, MACRO)   BHO_MOVE_REPEAT_I(x,MACRO)
#define BHO_MOVE_REPEAT_I(x, MACRO) BHO_MOVE_REPEAT##x(MACRO)
#define BHO_MOVE_REPEAT0(MACRO)
#define BHO_MOVE_REPEAT1(MACRO)                              MACRO
#define BHO_MOVE_REPEAT2(MACRO)  BHO_MOVE_REPEAT1(MACRO),  MACRO
#define BHO_MOVE_REPEAT3(MACRO)  BHO_MOVE_REPEAT2(MACRO),  MACRO
#define BHO_MOVE_REPEAT4(MACRO)  BHO_MOVE_REPEAT3(MACRO),  MACRO
#define BHO_MOVE_REPEAT5(MACRO)  BHO_MOVE_REPEAT4(MACRO),  MACRO
#define BHO_MOVE_REPEAT6(MACRO)  BHO_MOVE_REPEAT5(MACRO),  MACRO
#define BHO_MOVE_REPEAT7(MACRO)  BHO_MOVE_REPEAT6(MACRO),  MACRO
#define BHO_MOVE_REPEAT8(MACRO)  BHO_MOVE_REPEAT7(MACRO),  MACRO
#define BHO_MOVE_REPEAT9(MACRO)  BHO_MOVE_REPEAT8(MACRO),  MACRO
#define BHO_MOVE_REPEAT10(MACRO) BHO_MOVE_REPEAT9(MACRO),  MACRO
#define BHO_MOVE_REPEAT11(MACRO) BHO_MOVE_REPEAT10(MACRO), MACRO
#define BHO_MOVE_REPEAT12(MACRO) BHO_MOVE_REPEAT11(MACRO), MACRO
#define BHO_MOVE_REPEAT13(MACRO) BHO_MOVE_REPEAT12(MACRO), MACRO

//BHO_MOVE_FWDN
#define BHO_MOVE_FWD0
#define BHO_MOVE_FWD1                  ::bho::forward<P0>(p0)
#define BHO_MOVE_FWD2 BHO_MOVE_FWD1, ::bho::forward<P1>(p1)
#define BHO_MOVE_FWD3 BHO_MOVE_FWD2, ::bho::forward<P2>(p2)
#define BHO_MOVE_FWD4 BHO_MOVE_FWD3, ::bho::forward<P3>(p3)
#define BHO_MOVE_FWD5 BHO_MOVE_FWD4, ::bho::forward<P4>(p4)
#define BHO_MOVE_FWD6 BHO_MOVE_FWD5, ::bho::forward<P5>(p5)
#define BHO_MOVE_FWD7 BHO_MOVE_FWD6, ::bho::forward<P6>(p6)
#define BHO_MOVE_FWD8 BHO_MOVE_FWD7, ::bho::forward<P7>(p7)
#define BHO_MOVE_FWD9 BHO_MOVE_FWD8, ::bho::forward<P8>(p8)

//BHO_MOVE_FWDQN
#define BHO_MOVE_FWDQ0
#define BHO_MOVE_FWDQ1                   ::bho::forward<Q0>(q0)
#define BHO_MOVE_FWDQ2 BHO_MOVE_FWDQ1, ::bho::forward<Q1>(q1)
#define BHO_MOVE_FWDQ3 BHO_MOVE_FWDQ2, ::bho::forward<Q2>(q2)
#define BHO_MOVE_FWDQ4 BHO_MOVE_FWDQ3, ::bho::forward<Q3>(q3)
#define BHO_MOVE_FWDQ5 BHO_MOVE_FWDQ4, ::bho::forward<Q4>(q4)
#define BHO_MOVE_FWDQ6 BHO_MOVE_FWDQ5, ::bho::forward<Q5>(q5)
#define BHO_MOVE_FWDQ7 BHO_MOVE_FWDQ6, ::bho::forward<Q6>(q6)
#define BHO_MOVE_FWDQ8 BHO_MOVE_FWDQ7, ::bho::forward<Q7>(q7)
#define BHO_MOVE_FWDQ9 BHO_MOVE_FWDQ8, ::bho::forward<Q8>(q8)

//BHO_MOVE_TMPL_GETN
#define BHO_MOVE_TMPL_GET0
#define BHO_MOVE_TMPL_GET1                       p.template get<0>()
#define BHO_MOVE_TMPL_GET2 BHO_MOVE_TMPL_GET1, p.template get<1>()
#define BHO_MOVE_TMPL_GET3 BHO_MOVE_TMPL_GET2, p.template get<2>()
#define BHO_MOVE_TMPL_GET4 BHO_MOVE_TMPL_GET3, p.template get<3>()
#define BHO_MOVE_TMPL_GET5 BHO_MOVE_TMPL_GET4, p.template get<4>()
#define BHO_MOVE_TMPL_GET6 BHO_MOVE_TMPL_GET5, p.template get<5>()
#define BHO_MOVE_TMPL_GET7 BHO_MOVE_TMPL_GET6, p.template get<6>()
#define BHO_MOVE_TMPL_GET8 BHO_MOVE_TMPL_GET7, p.template get<7>()
#define BHO_MOVE_TMPL_GET9 BHO_MOVE_TMPL_GET8, p.template get<8>()

//BHO_MOVE_TMPL_GETQN
#define BHO_MOVE_TMPL_GETQ0
#define BHO_MOVE_TMPL_GETQ1                        q.template get<0>()
#define BHO_MOVE_TMPL_GETQ2 BHO_MOVE_TMPL_GETQ1, q.template get<1>()
#define BHO_MOVE_TMPL_GETQ3 BHO_MOVE_TMPL_GETQ2, q.template get<2>()
#define BHO_MOVE_TMPL_GETQ4 BHO_MOVE_TMPL_GETQ3, q.template get<3>()
#define BHO_MOVE_TMPL_GETQ5 BHO_MOVE_TMPL_GETQ4, q.template get<4>()
#define BHO_MOVE_TMPL_GETQ6 BHO_MOVE_TMPL_GETQ5, q.template get<5>()
#define BHO_MOVE_TMPL_GETQ7 BHO_MOVE_TMPL_GETQ6, q.template get<6>()
#define BHO_MOVE_TMPL_GETQ8 BHO_MOVE_TMPL_GETQ7, q.template get<7>()
#define BHO_MOVE_TMPL_GETQ9 BHO_MOVE_TMPL_GETQ8, q.template get<8>()

//BHO_MOVE_GET_IDXN
#define BHO_MOVE_GET_IDX0
#define BHO_MOVE_GET_IDX1                      get<0>(p)
#define BHO_MOVE_GET_IDX2 BHO_MOVE_GET_IDX1, get<1>(p)
#define BHO_MOVE_GET_IDX3 BHO_MOVE_GET_IDX2, get<2>(p)
#define BHO_MOVE_GET_IDX4 BHO_MOVE_GET_IDX3, get<3>(p)
#define BHO_MOVE_GET_IDX5 BHO_MOVE_GET_IDX4, get<4>(p)
#define BHO_MOVE_GET_IDX6 BHO_MOVE_GET_IDX5, get<5>(p)
#define BHO_MOVE_GET_IDX7 BHO_MOVE_GET_IDX6, get<6>(p)
#define BHO_MOVE_GET_IDX8 BHO_MOVE_GET_IDX7, get<7>(p)
#define BHO_MOVE_GET_IDX9 BHO_MOVE_GET_IDX8, get<8>(p)

//BHO_MOVE_GET_IDXQN
#define BHO_MOVE_GET_IDXQ0
#define BHO_MOVE_GET_IDXQ1                       get<0>(q)
#define BHO_MOVE_GET_IDXQ2 BHO_MOVE_GET_IDXQ1, get<1>(q)
#define BHO_MOVE_GET_IDXQ3 BHO_MOVE_GET_IDXQ2, get<2>(q)
#define BHO_MOVE_GET_IDXQ4 BHO_MOVE_GET_IDXQ3, get<3>(q)
#define BHO_MOVE_GET_IDXQ5 BHO_MOVE_GET_IDXQ4, get<4>(q)
#define BHO_MOVE_GET_IDXQ6 BHO_MOVE_GET_IDXQ5, get<5>(q)
#define BHO_MOVE_GET_IDXQ7 BHO_MOVE_GET_IDXQ6, get<6>(q)
#define BHO_MOVE_GET_IDXQ8 BHO_MOVE_GET_IDXQ7, get<7>(q)
#define BHO_MOVE_GET_IDXQ9 BHO_MOVE_GET_IDXQ8, get<8>(q)

//BHO_MOVE_ARGN
#define BHO_MOVE_ARG0
#define BHO_MOVE_ARG1                  p0
#define BHO_MOVE_ARG2 BHO_MOVE_ARG1, p1
#define BHO_MOVE_ARG3 BHO_MOVE_ARG2, p2
#define BHO_MOVE_ARG4 BHO_MOVE_ARG3, p3
#define BHO_MOVE_ARG5 BHO_MOVE_ARG4, p4
#define BHO_MOVE_ARG6 BHO_MOVE_ARG5, p5
#define BHO_MOVE_ARG7 BHO_MOVE_ARG6, p6
#define BHO_MOVE_ARG8 BHO_MOVE_ARG7, p7
#define BHO_MOVE_ARG9 BHO_MOVE_ARG8, p8

//BHO_MOVE_ARGQN
#define BHO_MOVE_ARGQ0
#define BHO_MOVE_ARGQ1                   q0
#define BHO_MOVE_ARGQ2 BHO_MOVE_ARGQ1, q1
#define BHO_MOVE_ARGQ3 BHO_MOVE_ARGQ2, q2
#define BHO_MOVE_ARGQ4 BHO_MOVE_ARGQ3, q3
#define BHO_MOVE_ARGQ5 BHO_MOVE_ARGQ4, q4
#define BHO_MOVE_ARGQ6 BHO_MOVE_ARGQ5, q5
#define BHO_MOVE_ARGQ7 BHO_MOVE_ARGQ6, q6
#define BHO_MOVE_ARGQ8 BHO_MOVE_ARGQ7, q7
#define BHO_MOVE_ARGQ9 BHO_MOVE_ARGQ8, q8

//BHO_MOVE_DECLVALN
#define BHO_MOVE_DECLVAL0
#define BHO_MOVE_DECLVAL1                      ::bho::move_detail::declval<P0>()
#define BHO_MOVE_DECLVAL2 BHO_MOVE_DECLVAL1, ::bho::move_detail::declval<P1>()
#define BHO_MOVE_DECLVAL3 BHO_MOVE_DECLVAL2, ::bho::move_detail::declval<P2>()
#define BHO_MOVE_DECLVAL4 BHO_MOVE_DECLVAL3, ::bho::move_detail::declval<P3>()
#define BHO_MOVE_DECLVAL5 BHO_MOVE_DECLVAL4, ::bho::move_detail::declval<P4>()
#define BHO_MOVE_DECLVAL6 BHO_MOVE_DECLVAL5, ::bho::move_detail::declval<P5>()
#define BHO_MOVE_DECLVAL7 BHO_MOVE_DECLVAL6, ::bho::move_detail::declval<P6>()
#define BHO_MOVE_DECLVAL8 BHO_MOVE_DECLVAL7, ::bho::move_detail::declval<P7>()
#define BHO_MOVE_DECLVAL9 BHO_MOVE_DECLVAL8, ::bho::move_detail::declval<P8>()

//BHO_MOVE_DECLVALQN
#define BHO_MOVE_DECLVALQ0
#define BHO_MOVE_DECLVALQ1                       ::bho::move_detail::declval<Q0>()
#define BHO_MOVE_DECLVALQ2 BHO_MOVE_DECLVALQ1, ::bho::move_detail::declval<Q1>()
#define BHO_MOVE_DECLVALQ3 BHO_MOVE_DECLVALQ2, ::bho::move_detail::declval<Q2>()
#define BHO_MOVE_DECLVALQ4 BHO_MOVE_DECLVALQ3, ::bho::move_detail::declval<Q3>()
#define BHO_MOVE_DECLVALQ5 BHO_MOVE_DECLVALQ4, ::bho::move_detail::declval<Q4>()
#define BHO_MOVE_DECLVALQ6 BHO_MOVE_DECLVALQ5, ::bho::move_detail::declval<Q5>()
#define BHO_MOVE_DECLVALQ7 BHO_MOVE_DECLVALQ6, ::bho::move_detail::declval<Q6>()
#define BHO_MOVE_DECLVALQ8 BHO_MOVE_DECLVALQ7, ::bho::move_detail::declval<Q7>()
#define BHO_MOVE_DECLVALQ9 BHO_MOVE_DECLVALQ8, ::bho::move_detail::declval<Q8>()

#ifdef BHO_MOVE_MSVC_10_MEMBER_RVALUE_REF_BUG
   #define BHO_MOVE_MREF(T)    ::bho::move_detail::mref<T>
   #define BHO_MOVE_MFWD(N)    ::bho::forward<P##N>(this->m_p##N.get())
   #define BHO_MOVE_MFWDQ(N)   ::bho::forward<Q##N>(this->m_q##N.get())
#else
   #define BHO_MOVE_MREF(T)    BHO_FWD_REF(T)
   #define BHO_MOVE_MFWD(N)    ::bho::forward<P##N>(this->m_p##N)
   #define BHO_MOVE_MFWDQ(N)   ::bho::forward<Q##N>(this->m_q##N)
#endif
#define BHO_MOVE_MITFWD(N)  *this->m_p##N
#define BHO_MOVE_MINC(N)    ++this->m_p##N
#define BHO_MOVE_MITFWDQ(N) *this->m_q##N
#define BHO_MOVE_MINCQ(N)   ++this->m_q##N


//BHO_MOVE_MFWDN
#define BHO_MOVE_MFWD0
#define BHO_MOVE_MFWD1                   BHO_MOVE_MFWD(0)
#define BHO_MOVE_MFWD2 BHO_MOVE_MFWD1, BHO_MOVE_MFWD(1)
#define BHO_MOVE_MFWD3 BHO_MOVE_MFWD2, BHO_MOVE_MFWD(2)
#define BHO_MOVE_MFWD4 BHO_MOVE_MFWD3, BHO_MOVE_MFWD(3)
#define BHO_MOVE_MFWD5 BHO_MOVE_MFWD4, BHO_MOVE_MFWD(4)
#define BHO_MOVE_MFWD6 BHO_MOVE_MFWD5, BHO_MOVE_MFWD(5)
#define BHO_MOVE_MFWD7 BHO_MOVE_MFWD6, BHO_MOVE_MFWD(6)
#define BHO_MOVE_MFWD8 BHO_MOVE_MFWD7, BHO_MOVE_MFWD(7)
#define BHO_MOVE_MFWD9 BHO_MOVE_MFWD8, BHO_MOVE_MFWD(8)

//BHO_MOVE_MFWDN
#define BHO_MOVE_MFWDQ0
#define BHO_MOVE_MFWDQ1                    BHO_MOVE_MFWDQ(0)
#define BHO_MOVE_MFWDQ2 BHO_MOVE_MFWDQ1, BHO_MOVE_MFWDQ(1)
#define BHO_MOVE_MFWDQ3 BHO_MOVE_MFWDQ2, BHO_MOVE_MFWDQ(2)
#define BHO_MOVE_MFWDQ4 BHO_MOVE_MFWDQ3, BHO_MOVE_MFWDQ(3)
#define BHO_MOVE_MFWDQ5 BHO_MOVE_MFWDQ4, BHO_MOVE_MFWDQ(4)
#define BHO_MOVE_MFWDQ6 BHO_MOVE_MFWDQ5, BHO_MOVE_MFWDQ(5)
#define BHO_MOVE_MFWDQ7 BHO_MOVE_MFWDQ6, BHO_MOVE_MFWDQ(6)
#define BHO_MOVE_MFWDQ8 BHO_MOVE_MFWDQ7, BHO_MOVE_MFWDQ(7)
#define BHO_MOVE_MFWDQ9 BHO_MOVE_MFWDQ8, BHO_MOVE_MFWDQ(8)

//BHO_MOVE_MINCN
#define BHO_MOVE_MINC0
#define BHO_MOVE_MINC1                   BHO_MOVE_MINC(0)
#define BHO_MOVE_MINC2 BHO_MOVE_MINC1, BHO_MOVE_MINC(1)
#define BHO_MOVE_MINC3 BHO_MOVE_MINC2, BHO_MOVE_MINC(2)
#define BHO_MOVE_MINC4 BHO_MOVE_MINC3, BHO_MOVE_MINC(3)
#define BHO_MOVE_MINC5 BHO_MOVE_MINC4, BHO_MOVE_MINC(4)
#define BHO_MOVE_MINC6 BHO_MOVE_MINC5, BHO_MOVE_MINC(5)
#define BHO_MOVE_MINC7 BHO_MOVE_MINC6, BHO_MOVE_MINC(6)
#define BHO_MOVE_MINC8 BHO_MOVE_MINC7, BHO_MOVE_MINC(7)
#define BHO_MOVE_MINC9 BHO_MOVE_MINC8, BHO_MOVE_MINC(8)

//BHO_MOVE_MINCQN
#define BHO_MOVE_MINCQ0
#define BHO_MOVE_MINCQ1                    BHO_MOVE_MINCQ(0)
#define BHO_MOVE_MINCQ2 BHO_MOVE_MINCQ1, BHO_MOVE_MINCQ(1)
#define BHO_MOVE_MINCQ3 BHO_MOVE_MINCQ2, BHO_MOVE_MINCQ(2)
#define BHO_MOVE_MINCQ4 BHO_MOVE_MINCQ3, BHO_MOVE_MINCQ(3)
#define BHO_MOVE_MINCQ5 BHO_MOVE_MINCQ4, BHO_MOVE_MINCQ(4)
#define BHO_MOVE_MINCQ6 BHO_MOVE_MINCQ5, BHO_MOVE_MINCQ(5)
#define BHO_MOVE_MINCQ7 BHO_MOVE_MINCQ6, BHO_MOVE_MINCQ(6)
#define BHO_MOVE_MINCQ8 BHO_MOVE_MINCQ7, BHO_MOVE_MINCQ(7)
#define BHO_MOVE_MINCQ9 BHO_MOVE_MINCQ8, BHO_MOVE_MINCQ(8)

//BHO_MOVE_MITFWDN
#define BHO_MOVE_MITFWD0
#define BHO_MOVE_MITFWD1                     BHO_MOVE_MITFWD(0)
#define BHO_MOVE_MITFWD2 BHO_MOVE_MITFWD1, BHO_MOVE_MITFWD(1)
#define BHO_MOVE_MITFWD3 BHO_MOVE_MITFWD2, BHO_MOVE_MITFWD(2)
#define BHO_MOVE_MITFWD4 BHO_MOVE_MITFWD3, BHO_MOVE_MITFWD(3)
#define BHO_MOVE_MITFWD5 BHO_MOVE_MITFWD4, BHO_MOVE_MITFWD(4)
#define BHO_MOVE_MITFWD6 BHO_MOVE_MITFWD5, BHO_MOVE_MITFWD(5)
#define BHO_MOVE_MITFWD7 BHO_MOVE_MITFWD6, BHO_MOVE_MITFWD(6)
#define BHO_MOVE_MITFWD8 BHO_MOVE_MITFWD7, BHO_MOVE_MITFWD(7)
#define BHO_MOVE_MITFWD9 BHO_MOVE_MITFWD8, BHO_MOVE_MITFWD(8)

//BHO_MOVE_MITFWDQN
#define BHO_MOVE_MITFWDQ0
#define BHO_MOVE_MITFWDQ1                      BHO_MOVE_MITFWDQ(0)
#define BHO_MOVE_MITFWDQ2 BHO_MOVE_MITFWDQ1, BHO_MOVE_MITFWDQ(1)
#define BHO_MOVE_MITFWDQ3 BHO_MOVE_MITFWDQ2, BHO_MOVE_MITFWDQ(2)
#define BHO_MOVE_MITFWDQ4 BHO_MOVE_MITFWDQ3, BHO_MOVE_MITFWDQ(3)
#define BHO_MOVE_MITFWDQ5 BHO_MOVE_MITFWDQ4, BHO_MOVE_MITFWDQ(4)
#define BHO_MOVE_MITFWDQ6 BHO_MOVE_MITFWDQ5, BHO_MOVE_MITFWDQ(5)
#define BHO_MOVE_MITFWDQ7 BHO_MOVE_MITFWDQ6, BHO_MOVE_MITFWDQ(6)
#define BHO_MOVE_MITFWDQ8 BHO_MOVE_MITFWDQ7, BHO_MOVE_MITFWDQ(7)
#define BHO_MOVE_MITFWDQ9 BHO_MOVE_MITFWDQ8, BHO_MOVE_MITFWDQ(8)

//BHO_MOVE_FWD_INITN
#define BHO_MOVE_FWD_INIT0
#define BHO_MOVE_FWD_INIT1                       m_p0(::bho::forward<P0>(p0))
#define BHO_MOVE_FWD_INIT2 BHO_MOVE_FWD_INIT1, m_p1(::bho::forward<P1>(p1))
#define BHO_MOVE_FWD_INIT3 BHO_MOVE_FWD_INIT2, m_p2(::bho::forward<P2>(p2))
#define BHO_MOVE_FWD_INIT4 BHO_MOVE_FWD_INIT3, m_p3(::bho::forward<P3>(p3))
#define BHO_MOVE_FWD_INIT5 BHO_MOVE_FWD_INIT4, m_p4(::bho::forward<P4>(p4))
#define BHO_MOVE_FWD_INIT6 BHO_MOVE_FWD_INIT5, m_p5(::bho::forward<P5>(p5))
#define BHO_MOVE_FWD_INIT7 BHO_MOVE_FWD_INIT6, m_p6(::bho::forward<P6>(p6))
#define BHO_MOVE_FWD_INIT8 BHO_MOVE_FWD_INIT7, m_p7(::bho::forward<P7>(p7))
#define BHO_MOVE_FWD_INIT9 BHO_MOVE_FWD_INIT8, m_p8(::bho::forward<P8>(p8))

//BHO_MOVE_FWD_INITQN
#define BHO_MOVE_FWD_INITQ0
#define BHO_MOVE_FWD_INITQ1                        m_q0(::bho::forward<Q0>(q0))
#define BHO_MOVE_FWD_INITQ2 BHO_MOVE_FWD_INITQ1, m_q1(::bho::forward<Q1>(q1))
#define BHO_MOVE_FWD_INITQ3 BHO_MOVE_FWD_INITQ2, m_q2(::bho::forward<Q2>(q2))
#define BHO_MOVE_FWD_INITQ4 BHO_MOVE_FWD_INITQ3, m_q3(::bho::forward<Q3>(q3))
#define BHO_MOVE_FWD_INITQ5 BHO_MOVE_FWD_INITQ4, m_q4(::bho::forward<Q4>(q4))
#define BHO_MOVE_FWD_INITQ6 BHO_MOVE_FWD_INITQ5, m_q5(::bho::forward<Q5>(q5))
#define BHO_MOVE_FWD_INITQ7 BHO_MOVE_FWD_INITQ6, m_q6(::bho::forward<Q6>(q6))
#define BHO_MOVE_FWD_INITQ8 BHO_MOVE_FWD_INITQ7, m_q7(::bho::forward<Q7>(q7))
#define BHO_MOVE_FWD_INITQ9 BHO_MOVE_FWD_INITQ8, m_q8(::bho::forward<Q8>(q8))

//BHO_MOVE_VAL_INITN
#define BHO_MOVE_VAL_INIT0
#define BHO_MOVE_VAL_INIT1                       m_p0(p0)
#define BHO_MOVE_VAL_INIT2 BHO_MOVE_VAL_INIT1, m_p1(p1)
#define BHO_MOVE_VAL_INIT3 BHO_MOVE_VAL_INIT2, m_p2(p2)
#define BHO_MOVE_VAL_INIT4 BHO_MOVE_VAL_INIT3, m_p3(p3)
#define BHO_MOVE_VAL_INIT5 BHO_MOVE_VAL_INIT4, m_p4(p4)
#define BHO_MOVE_VAL_INIT6 BHO_MOVE_VAL_INIT5, m_p5(p5)
#define BHO_MOVE_VAL_INIT7 BHO_MOVE_VAL_INIT6, m_p6(p6)
#define BHO_MOVE_VAL_INIT8 BHO_MOVE_VAL_INIT7, m_p7(p7)
#define BHO_MOVE_VAL_INIT9 BHO_MOVE_VAL_INIT8, m_p8(p8)

//BHO_MOVE_VAL_INITQN
#define BHO_MOVE_VAL_INITQ0
#define BHO_MOVE_VAL_INITQ1                        m_q0(q0)
#define BHO_MOVE_VAL_INITQ2 BHO_MOVE_VAL_INITQ1, m_q1(q1)
#define BHO_MOVE_VAL_INITQ3 BHO_MOVE_VAL_INITQ2, m_q2(q2)
#define BHO_MOVE_VAL_INITQ4 BHO_MOVE_VAL_INITQ3, m_q3(q3)
#define BHO_MOVE_VAL_INITQ5 BHO_MOVE_VAL_INITQ4, m_q4(q4)
#define BHO_MOVE_VAL_INITQ6 BHO_MOVE_VAL_INITQ5, m_q5(q5)
#define BHO_MOVE_VAL_INITQ7 BHO_MOVE_VAL_INITQ6, m_q6(q6)
#define BHO_MOVE_VAL_INITQ8 BHO_MOVE_VAL_INITQ7, m_q7(q7)
#define BHO_MOVE_VAL_INITQ9 BHO_MOVE_VAL_INITQ8, m_q8(q8)

//BHO_MOVE_UREFANONN
#define BHO_MOVE_UREFANON0
#define BHO_MOVE_UREFANON1                       BHO_FWD_REF(P0)
#define BHO_MOVE_UREFANON2 BHO_MOVE_UREFANON1, BHO_FWD_REF(P1)
#define BHO_MOVE_UREFANON3 BHO_MOVE_UREFANON2, BHO_FWD_REF(P2)
#define BHO_MOVE_UREFANON4 BHO_MOVE_UREFANON3, BHO_FWD_REF(P3)
#define BHO_MOVE_UREFANON5 BHO_MOVE_UREFANON4, BHO_FWD_REF(P4)
#define BHO_MOVE_UREFANON6 BHO_MOVE_UREFANON5, BHO_FWD_REF(P5)
#define BHO_MOVE_UREFANON7 BHO_MOVE_UREFANON6, BHO_FWD_REF(P6)
#define BHO_MOVE_UREFANON8 BHO_MOVE_UREFANON7, BHO_FWD_REF(P7)
#define BHO_MOVE_UREFANON9 BHO_MOVE_UREFANON8, BHO_FWD_REF(P8)

//BHO_MOVE_UREFN
#define BHO_MOVE_UREF0
#define BHO_MOVE_UREF1                   BHO_FWD_REF(P0) p0
#define BHO_MOVE_UREF2 BHO_MOVE_UREF1, BHO_FWD_REF(P1) p1
#define BHO_MOVE_UREF3 BHO_MOVE_UREF2, BHO_FWD_REF(P2) p2
#define BHO_MOVE_UREF4 BHO_MOVE_UREF3, BHO_FWD_REF(P3) p3
#define BHO_MOVE_UREF5 BHO_MOVE_UREF4, BHO_FWD_REF(P4) p4
#define BHO_MOVE_UREF6 BHO_MOVE_UREF5, BHO_FWD_REF(P5) p5
#define BHO_MOVE_UREF7 BHO_MOVE_UREF6, BHO_FWD_REF(P6) p6
#define BHO_MOVE_UREF8 BHO_MOVE_UREF7, BHO_FWD_REF(P7) p7
#define BHO_MOVE_UREF9 BHO_MOVE_UREF8, BHO_FWD_REF(P8) p8

//BHO_MOVE_UREFQN
#define BHO_MOVE_UREFQ0
#define BHO_MOVE_UREFQ1                    BHO_FWD_REF(Q0) q0
#define BHO_MOVE_UREFQ2 BHO_MOVE_UREFQ1, BHO_FWD_REF(Q1) q1
#define BHO_MOVE_UREFQ3 BHO_MOVE_UREFQ2, BHO_FWD_REF(Q2) q2
#define BHO_MOVE_UREFQ4 BHO_MOVE_UREFQ3, BHO_FWD_REF(Q3) q3
#define BHO_MOVE_UREFQ5 BHO_MOVE_UREFQ4, BHO_FWD_REF(Q4) q4
#define BHO_MOVE_UREFQ6 BHO_MOVE_UREFQ5, BHO_FWD_REF(Q5) q5
#define BHO_MOVE_UREFQ7 BHO_MOVE_UREFQ6, BHO_FWD_REF(Q6) q6
#define BHO_MOVE_UREFQ8 BHO_MOVE_UREFQ7, BHO_FWD_REF(Q7) q7
#define BHO_MOVE_UREFQ9 BHO_MOVE_UREFQ8, BHO_FWD_REF(Q8) q8

//BHO_MOVE_VALN
#define BHO_MOVE_VAL0
#define BHO_MOVE_VAL1                  BHO_FWD_REF(P0) p0
#define BHO_MOVE_VAL2 BHO_MOVE_VAL1, BHO_FWD_REF(P1) p1
#define BHO_MOVE_VAL3 BHO_MOVE_VAL2, BHO_FWD_REF(P2) p2
#define BHO_MOVE_VAL4 BHO_MOVE_VAL3, BHO_FWD_REF(P3) p3
#define BHO_MOVE_VAL5 BHO_MOVE_VAL4, BHO_FWD_REF(P4) p4
#define BHO_MOVE_VAL6 BHO_MOVE_VAL5, BHO_FWD_REF(P5) p5
#define BHO_MOVE_VAL7 BHO_MOVE_VAL6, BHO_FWD_REF(P6) p6
#define BHO_MOVE_VAL8 BHO_MOVE_VAL7, BHO_FWD_REF(P7) p7
#define BHO_MOVE_VAL9 BHO_MOVE_VAL8, BHO_FWD_REF(P8) p8

//BHO_MOVE_VALQN
#define BHO_MOVE_VALQ0
#define BHO_MOVE_VALQ1                   BHO_FWD_REF(Q0) q0
#define BHO_MOVE_VALQ2 BHO_MOVE_VALQ1, BHO_FWD_REF(Q1) q1
#define BHO_MOVE_VALQ3 BHO_MOVE_VALQ2, BHO_FWD_REF(Q2) q2
#define BHO_MOVE_VALQ4 BHO_MOVE_VALQ3, BHO_FWD_REF(Q3) q3
#define BHO_MOVE_VALQ5 BHO_MOVE_VALQ4, BHO_FWD_REF(Q4) q4
#define BHO_MOVE_VALQ6 BHO_MOVE_VALQ5, BHO_FWD_REF(Q5) q5
#define BHO_MOVE_VALQ7 BHO_MOVE_VALQ6, BHO_FWD_REF(Q6) q6
#define BHO_MOVE_VALQ8 BHO_MOVE_VALQ7, BHO_FWD_REF(Q7) q7
#define BHO_MOVE_VALQ9 BHO_MOVE_VALQ8, BHO_FWD_REF(Q8) q8


#define BHO_MOVE_UNVOIDCREF(T) const typename bho::move_detail::unvoid<T>::type&
//BHO_MOVE_CREFN
#define BHO_MOVE_CREF0
#define BHO_MOVE_CREF1                   BHO_MOVE_UNVOIDCREF(P0) p0
#define BHO_MOVE_CREF2 BHO_MOVE_CREF1, BHO_MOVE_UNVOIDCREF(P1) p1
#define BHO_MOVE_CREF3 BHO_MOVE_CREF2, BHO_MOVE_UNVOIDCREF(P2) p2
#define BHO_MOVE_CREF4 BHO_MOVE_CREF3, BHO_MOVE_UNVOIDCREF(P3) p3
#define BHO_MOVE_CREF5 BHO_MOVE_CREF4, BHO_MOVE_UNVOIDCREF(P4) p4
#define BHO_MOVE_CREF6 BHO_MOVE_CREF5, BHO_MOVE_UNVOIDCREF(P5) p5
#define BHO_MOVE_CREF7 BHO_MOVE_CREF6, BHO_MOVE_UNVOIDCREF(P6) p6
#define BHO_MOVE_CREF8 BHO_MOVE_CREF7, BHO_MOVE_UNVOIDCREF(P7) p7
#define BHO_MOVE_CREF9 BHO_MOVE_CREF8, BHO_MOVE_UNVOIDCREF(P8) p8

//BHO_MOVE_CREFQN
#define BHO_MOVE_CREFQ0
#define BHO_MOVE_CREFQ1                    BHO_MOVE_UNVOIDCREF(Q0) q0
#define BHO_MOVE_CREFQ2 BHO_MOVE_CREFQ1, BHO_MOVE_UNVOIDCREF(Q1) q1
#define BHO_MOVE_CREFQ3 BHO_MOVE_CREFQ2, BHO_MOVE_UNVOIDCREF(Q2) q2
#define BHO_MOVE_CREFQ4 BHO_MOVE_CREFQ3, BHO_MOVE_UNVOIDCREF(Q3) q3
#define BHO_MOVE_CREFQ5 BHO_MOVE_CREFQ4, BHO_MOVE_UNVOIDCREF(Q4) q4
#define BHO_MOVE_CREFQ6 BHO_MOVE_CREFQ5, BHO_MOVE_UNVOIDCREF(Q5) q5
#define BHO_MOVE_CREFQ7 BHO_MOVE_CREFQ6, BHO_MOVE_UNVOIDCREF(Q6) q6
#define BHO_MOVE_CREFQ8 BHO_MOVE_CREFQ7, BHO_MOVE_UNVOIDCREF(Q7) q7
#define BHO_MOVE_CREFQ9 BHO_MOVE_CREFQ8, BHO_MOVE_UNVOIDCREF(Q8) q8

//BHO_MOVE_CLASSN
#define BHO_MOVE_CLASS0
#define BHO_MOVE_CLASS1                    class P0
#define BHO_MOVE_CLASS2 BHO_MOVE_CLASS1, class P1
#define BHO_MOVE_CLASS3 BHO_MOVE_CLASS2, class P2
#define BHO_MOVE_CLASS4 BHO_MOVE_CLASS3, class P3
#define BHO_MOVE_CLASS5 BHO_MOVE_CLASS4, class P4
#define BHO_MOVE_CLASS6 BHO_MOVE_CLASS5, class P5
#define BHO_MOVE_CLASS7 BHO_MOVE_CLASS6, class P6
#define BHO_MOVE_CLASS8 BHO_MOVE_CLASS7, class P7
#define BHO_MOVE_CLASS9 BHO_MOVE_CLASS8, class P8

//BHO_MOVE_CLASSQN
#define BHO_MOVE_CLASSQ0
#define BHO_MOVE_CLASSQ1                     class Q0
#define BHO_MOVE_CLASSQ2 BHO_MOVE_CLASSQ1, class Q1
#define BHO_MOVE_CLASSQ3 BHO_MOVE_CLASSQ2, class Q2
#define BHO_MOVE_CLASSQ4 BHO_MOVE_CLASSQ3, class Q3
#define BHO_MOVE_CLASSQ5 BHO_MOVE_CLASSQ4, class Q4
#define BHO_MOVE_CLASSQ6 BHO_MOVE_CLASSQ5, class Q5
#define BHO_MOVE_CLASSQ7 BHO_MOVE_CLASSQ6, class Q6
#define BHO_MOVE_CLASSQ8 BHO_MOVE_CLASSQ7, class Q7
#define BHO_MOVE_CLASSQ9 BHO_MOVE_CLASSQ8, class Q8

//BHO_MOVE_CLASSDFLTN
#define BHO_MOVE_CLASSDFLT0
#define BHO_MOVE_CLASSDFLT1                        class P0 = void
#define BHO_MOVE_CLASSDFLT2 BHO_MOVE_CLASSDFLT1, class P1 = void
#define BHO_MOVE_CLASSDFLT3 BHO_MOVE_CLASSDFLT2, class P2 = void
#define BHO_MOVE_CLASSDFLT4 BHO_MOVE_CLASSDFLT3, class P3 = void
#define BHO_MOVE_CLASSDFLT5 BHO_MOVE_CLASSDFLT4, class P4 = void
#define BHO_MOVE_CLASSDFLT6 BHO_MOVE_CLASSDFLT5, class P5 = void
#define BHO_MOVE_CLASSDFLT7 BHO_MOVE_CLASSDFLT6, class P6 = void
#define BHO_MOVE_CLASSDFLT8 BHO_MOVE_CLASSDFLT7, class P7 = void
#define BHO_MOVE_CLASSDFLT9 BHO_MOVE_CLASSDFLT8, class P8 = void

//BHO_MOVE_CLASSDFLTQN
#define BHO_MOVE_CLASSDFLTQ0
#define BHO_MOVE_CLASSDFLTQ1                         class Q0 = void
#define BHO_MOVE_CLASSDFLTQ2 BHO_MOVE_CLASSDFLTQ1, class Q1 = void
#define BHO_MOVE_CLASSDFLTQ3 BHO_MOVE_CLASSDFLTQ2, class Q2 = void
#define BHO_MOVE_CLASSDFLTQ4 BHO_MOVE_CLASSDFLTQ3, class Q3 = void
#define BHO_MOVE_CLASSDFLTQ5 BHO_MOVE_CLASSDFLTQ4, class Q4 = void
#define BHO_MOVE_CLASSDFLTQ6 BHO_MOVE_CLASSDFLTQ5, class Q5 = void
#define BHO_MOVE_CLASSDFLTQ7 BHO_MOVE_CLASSDFLTQ6, class Q6 = void
#define BHO_MOVE_CLASSDFLTQ8 BHO_MOVE_CLASSDFLTQ7, class Q7 = void
#define BHO_MOVE_CLASSDFLTQ9 BHO_MOVE_CLASSDFLTQ8, class Q8 = void

//BHO_MOVE_LAST_TARGN
#define BHO_MOVE_LAST_TARG0 void
#define BHO_MOVE_LAST_TARG1 P0
#define BHO_MOVE_LAST_TARG2 P1
#define BHO_MOVE_LAST_TARG3 P2
#define BHO_MOVE_LAST_TARG4 P3
#define BHO_MOVE_LAST_TARG5 P4
#define BHO_MOVE_LAST_TARG6 P5
#define BHO_MOVE_LAST_TARG7 P6
#define BHO_MOVE_LAST_TARG8 P7
#define BHO_MOVE_LAST_TARG9 P8

//BHO_MOVE_LAST_TARGQN
#define BHO_MOVE_LAST_TARGQ0 void
#define BHO_MOVE_LAST_TARGQ1 Q0
#define BHO_MOVE_LAST_TARGQ2 Q1
#define BHO_MOVE_LAST_TARGQ3 Q2
#define BHO_MOVE_LAST_TARGQ4 Q3
#define BHO_MOVE_LAST_TARGQ5 Q4
#define BHO_MOVE_LAST_TARGQ6 Q5
#define BHO_MOVE_LAST_TARGQ7 Q6
#define BHO_MOVE_LAST_TARGQ8 Q7
#define BHO_MOVE_LAST_TARGQ9 Q8


//BHO_MOVE_TARGN
#define BHO_MOVE_TARG0
#define BHO_MOVE_TARG1                   P0
#define BHO_MOVE_TARG2 BHO_MOVE_TARG1, P1
#define BHO_MOVE_TARG3 BHO_MOVE_TARG2, P2
#define BHO_MOVE_TARG4 BHO_MOVE_TARG3, P3
#define BHO_MOVE_TARG5 BHO_MOVE_TARG4, P4
#define BHO_MOVE_TARG6 BHO_MOVE_TARG5, P5
#define BHO_MOVE_TARG7 BHO_MOVE_TARG6, P6
#define BHO_MOVE_TARG8 BHO_MOVE_TARG7, P7
#define BHO_MOVE_TARG9 BHO_MOVE_TARG8, P8

//BHO_MOVE_TARGQN
#define BHO_MOVE_TARGQ0
#define BHO_MOVE_TARGQ1                    Q0
#define BHO_MOVE_TARGQ2 BHO_MOVE_TARGQ1, Q1
#define BHO_MOVE_TARGQ3 BHO_MOVE_TARGQ2, Q2
#define BHO_MOVE_TARGQ4 BHO_MOVE_TARGQ3, Q3
#define BHO_MOVE_TARGQ5 BHO_MOVE_TARGQ4, Q4
#define BHO_MOVE_TARGQ6 BHO_MOVE_TARGQ5, Q5
#define BHO_MOVE_TARGQ7 BHO_MOVE_TARGQ6, Q6
#define BHO_MOVE_TARGQ8 BHO_MOVE_TARGQ7, Q7
#define BHO_MOVE_TARGQ9 BHO_MOVE_TARGQ8, Q8

//BHO_MOVE_FWD_TN
#define BHO_MOVE_FWD_T0
#define BHO_MOVE_FWD_T1                    typename ::bho::move_detail::forward_type<P0>::type
#define BHO_MOVE_FWD_T2 BHO_MOVE_FWD_T1, typename ::bho::move_detail::forward_type<P1>::type
#define BHO_MOVE_FWD_T3 BHO_MOVE_FWD_T2, typename ::bho::move_detail::forward_type<P2>::type
#define BHO_MOVE_FWD_T4 BHO_MOVE_FWD_T3, typename ::bho::move_detail::forward_type<P3>::type
#define BHO_MOVE_FWD_T5 BHO_MOVE_FWD_T4, typename ::bho::move_detail::forward_type<P4>::type
#define BHO_MOVE_FWD_T6 BHO_MOVE_FWD_T5, typename ::bho::move_detail::forward_type<P5>::type
#define BHO_MOVE_FWD_T7 BHO_MOVE_FWD_T6, typename ::bho::move_detail::forward_type<P6>::type
#define BHO_MOVE_FWD_T8 BHO_MOVE_FWD_T7, typename ::bho::move_detail::forward_type<P7>::type
#define BHO_MOVE_FWD_T9 BHO_MOVE_FWD_T8, typename ::bho::move_detail::forward_type<P8>::type

//BHO_MOVE_FWD_TQN
#define BHO_MOVE_FWD_TQ0
#define BHO_MOVE_FWD_TQ1                     typename ::bho::move_detail::forward_type<Q0>::type
#define BHO_MOVE_FWD_TQ2 BHO_MOVE_FWD_TQ1, typename ::bho::move_detail::forward_type<Q1>::type
#define BHO_MOVE_FWD_TQ3 BHO_MOVE_FWD_TQ2, typename ::bho::move_detail::forward_type<Q2>::type
#define BHO_MOVE_FWD_TQ4 BHO_MOVE_FWD_TQ3, typename ::bho::move_detail::forward_type<Q3>::type
#define BHO_MOVE_FWD_TQ5 BHO_MOVE_FWD_TQ4, typename ::bho::move_detail::forward_type<Q4>::type
#define BHO_MOVE_FWD_TQ6 BHO_MOVE_FWD_TQ5, typename ::bho::move_detail::forward_type<Q5>::type
#define BHO_MOVE_FWD_TQ7 BHO_MOVE_FWD_TQ6, typename ::bho::move_detail::forward_type<Q6>::type
#define BHO_MOVE_FWD_TQ8 BHO_MOVE_FWD_TQ7, typename ::bho::move_detail::forward_type<Q7>::type
#define BHO_MOVE_FWD_TQ9 BHO_MOVE_FWD_TQ8, typename ::bho::move_detail::forward_type<Q8>::type

//BHO_MOVE_MREFX
#define BHO_MOVE_MREF0
#define BHO_MOVE_MREF1                  BHO_MOVE_MREF(P0) m_p0;
#define BHO_MOVE_MREF2 BHO_MOVE_MREF1 BHO_MOVE_MREF(P1) m_p1;
#define BHO_MOVE_MREF3 BHO_MOVE_MREF2 BHO_MOVE_MREF(P2) m_p2;
#define BHO_MOVE_MREF4 BHO_MOVE_MREF3 BHO_MOVE_MREF(P3) m_p3;
#define BHO_MOVE_MREF5 BHO_MOVE_MREF4 BHO_MOVE_MREF(P4) m_p4;
#define BHO_MOVE_MREF6 BHO_MOVE_MREF5 BHO_MOVE_MREF(P5) m_p5;
#define BHO_MOVE_MREF7 BHO_MOVE_MREF6 BHO_MOVE_MREF(P6) m_p6;
#define BHO_MOVE_MREF8 BHO_MOVE_MREF7 BHO_MOVE_MREF(P7) m_p7;
#define BHO_MOVE_MREF9 BHO_MOVE_MREF8 BHO_MOVE_MREF(P8) m_p8;

//BHO_MOVE_MREFQX
#define BHO_MOVE_MREFQ0
#define BHO_MOVE_MREFQ1                   BHO_MOVE_MREFQ(Q0) m_q0;
#define BHO_MOVE_MREFQ2 BHO_MOVE_MREFQ1 BHO_MOVE_MREFQ(Q1) m_q1;
#define BHO_MOVE_MREFQ3 BHO_MOVE_MREFQ2 BHO_MOVE_MREFQ(Q2) m_q2;
#define BHO_MOVE_MREFQ4 BHO_MOVE_MREFQ3 BHO_MOVE_MREFQ(Q3) m_q3;
#define BHO_MOVE_MREFQ5 BHO_MOVE_MREFQ4 BHO_MOVE_MREFQ(Q4) m_q4;
#define BHO_MOVE_MREFQ6 BHO_MOVE_MREFQ5 BHO_MOVE_MREFQ(Q5) m_q5;
#define BHO_MOVE_MREFQ7 BHO_MOVE_MREFQ6 BHO_MOVE_MREFQ(Q6) m_q6;
#define BHO_MOVE_MREFQ8 BHO_MOVE_MREFQ7 BHO_MOVE_MREFQ(Q7) m_q7;
#define BHO_MOVE_MREFQ9 BHO_MOVE_MREFQ8 BHO_MOVE_MREFQ(Q8) m_q8;

//BHO_MOVE_MEMBX
#define BHO_MOVE_MEMB0
#define BHO_MOVE_MEMB1                  P0 m_p0;
#define BHO_MOVE_MEMB2 BHO_MOVE_MEMB1 P1 m_p1;
#define BHO_MOVE_MEMB3 BHO_MOVE_MEMB2 P2 m_p2;
#define BHO_MOVE_MEMB4 BHO_MOVE_MEMB3 P3 m_p3;
#define BHO_MOVE_MEMB5 BHO_MOVE_MEMB4 P4 m_p4;
#define BHO_MOVE_MEMB6 BHO_MOVE_MEMB5 P5 m_p5;
#define BHO_MOVE_MEMB7 BHO_MOVE_MEMB6 P6 m_p6;
#define BHO_MOVE_MEMB8 BHO_MOVE_MEMB7 P7 m_p7;
#define BHO_MOVE_MEMB9 BHO_MOVE_MEMB8 P8 m_p8;

//BHO_MOVE_MEMBQX
#define BHO_MOVE_MEMBQ0
#define BHO_MOVE_MEMBQ1                   Q0 m_q0;
#define BHO_MOVE_MEMBQ2 BHO_MOVE_MEMBQ1 Q1 m_q1;
#define BHO_MOVE_MEMBQ3 BHO_MOVE_MEMBQ2 Q2 m_q2;
#define BHO_MOVE_MEMBQ4 BHO_MOVE_MEMBQ3 Q3 m_q3;
#define BHO_MOVE_MEMBQ5 BHO_MOVE_MEMBQ4 Q4 m_q4;
#define BHO_MOVE_MEMBQ6 BHO_MOVE_MEMBQ5 Q5 m_q5;
#define BHO_MOVE_MEMBQ7 BHO_MOVE_MEMBQ6 Q6 m_q6;
#define BHO_MOVE_MEMBQ8 BHO_MOVE_MEMBQ7 Q7 m_q7;
#define BHO_MOVE_MEMBQ9 BHO_MOVE_MEMBQ8 Q8 m_q8;

//BHO_MOVE_TMPL_LTN
#define BHO_MOVE_TMPL_LT0
#define BHO_MOVE_TMPL_LT1 template<
#define BHO_MOVE_TMPL_LT2 BHO_MOVE_TMPL_LT1
#define BHO_MOVE_TMPL_LT3 BHO_MOVE_TMPL_LT1
#define BHO_MOVE_TMPL_LT4 BHO_MOVE_TMPL_LT1
#define BHO_MOVE_TMPL_LT5 BHO_MOVE_TMPL_LT1
#define BHO_MOVE_TMPL_LT6 BHO_MOVE_TMPL_LT1
#define BHO_MOVE_TMPL_LT7 BHO_MOVE_TMPL_LT1
#define BHO_MOVE_TMPL_LT8 BHO_MOVE_TMPL_LT1
#define BHO_MOVE_TMPL_LT9 BHO_MOVE_TMPL_LT1

//BHO_MOVE_LTN
#define BHO_MOVE_LT0
#define BHO_MOVE_LT1 <
#define BHO_MOVE_LT2 BHO_MOVE_LT1
#define BHO_MOVE_LT3 BHO_MOVE_LT1
#define BHO_MOVE_LT4 BHO_MOVE_LT1
#define BHO_MOVE_LT5 BHO_MOVE_LT1
#define BHO_MOVE_LT6 BHO_MOVE_LT1
#define BHO_MOVE_LT7 BHO_MOVE_LT1
#define BHO_MOVE_LT8 BHO_MOVE_LT1
#define BHO_MOVE_LT9 BHO_MOVE_LT1

//BHO_MOVE_GTN
#define BHO_MOVE_GT0
#define BHO_MOVE_GT1 >
#define BHO_MOVE_GT2 BHO_MOVE_GT1
#define BHO_MOVE_GT3 BHO_MOVE_GT1
#define BHO_MOVE_GT4 BHO_MOVE_GT1
#define BHO_MOVE_GT5 BHO_MOVE_GT1
#define BHO_MOVE_GT6 BHO_MOVE_GT1
#define BHO_MOVE_GT7 BHO_MOVE_GT1
#define BHO_MOVE_GT8 BHO_MOVE_GT1
#define BHO_MOVE_GT9 BHO_MOVE_GT1

//BHO_MOVE_LPN
#define BHO_MOVE_LP0
#define BHO_MOVE_LP1 (
#define BHO_MOVE_LP2 BHO_MOVE_LP1
#define BHO_MOVE_LP3 BHO_MOVE_LP1
#define BHO_MOVE_LP4 BHO_MOVE_LP1
#define BHO_MOVE_LP5 BHO_MOVE_LP1
#define BHO_MOVE_LP6 BHO_MOVE_LP1
#define BHO_MOVE_LP7 BHO_MOVE_LP1
#define BHO_MOVE_LP8 BHO_MOVE_LP1
#define BHO_MOVE_LP9 BHO_MOVE_LP1

//BHO_MOVE_RPN
#define BHO_MOVE_RP0
#define BHO_MOVE_RP1 )
#define BHO_MOVE_RP2 BHO_MOVE_RP1
#define BHO_MOVE_RP3 BHO_MOVE_RP1
#define BHO_MOVE_RP4 BHO_MOVE_RP1
#define BHO_MOVE_RP5 BHO_MOVE_RP1
#define BHO_MOVE_RP6 BHO_MOVE_RP1
#define BHO_MOVE_RP7 BHO_MOVE_RP1
#define BHO_MOVE_RP8 BHO_MOVE_RP1
#define BHO_MOVE_RP9 BHO_MOVE_RP1

//BHO_MOVE_IN
#define BHO_MOVE_I0
#define BHO_MOVE_I1 ,
#define BHO_MOVE_I2 BHO_MOVE_I1
#define BHO_MOVE_I3 BHO_MOVE_I1
#define BHO_MOVE_I4 BHO_MOVE_I1
#define BHO_MOVE_I5 BHO_MOVE_I1
#define BHO_MOVE_I6 BHO_MOVE_I1
#define BHO_MOVE_I7 BHO_MOVE_I1
#define BHO_MOVE_I8 BHO_MOVE_I1
#define BHO_MOVE_I9 BHO_MOVE_I1

//BHO_MOVE_BOOL
# define BHO_MOVE_BOOL(x)   BHO_MOVE_BOOL_I(x)
# define BHO_MOVE_BOOL_I(x) BHO_MOVE_BOOL##x
# define BHO_MOVE_BOOL0 0
# define BHO_MOVE_BOOL1 1
# define BHO_MOVE_BOOL2 1
# define BHO_MOVE_BOOL3 1
# define BHO_MOVE_BOOL4 1
# define BHO_MOVE_BOOL5 1
# define BHO_MOVE_BOOL6 1
# define BHO_MOVE_BOOL7 1
# define BHO_MOVE_BOOL8 1
# define BHO_MOVE_BOOL9 1

//BHO_MOVE_I_IF
#define BHO_MOVE_I_IF(x)    BHO_MOVE_I_IF_I (BHO_MOVE_BOOL(x))
#define BHO_MOVE_I_IF_I(x)  BHO_MOVE_I_IF_I2(x)
#define BHO_MOVE_I_IF_I2(x) BHO_MOVE_IF_I_##x
#define BHO_MOVE_IF_I_0
#define BHO_MOVE_IF_I_1 ,

//BHO_MOVE_IF
#define BHO_MOVE_IF(cond, t, f) BHO_MOVE_IF_I(cond, t, f)
#define BHO_MOVE_IF_I(cond, t, f) BHO_MOVE_IIF(BHO_MOVE_BOOL(cond), t, f)

#define BHO_MOVE_IIF(bit, t, f)   BHO_MOVE_IIF_I(bit, t, f)
#define BHO_MOVE_IIF_I(bit, t, f) BHO_MOVE_IIF_##bit(t, f)
#define BHO_MOVE_IIF_0(t, f) f
#define BHO_MOVE_IIF_1(t, f) t

/*
#define BHO_MOVE_IIF(bit, t, f) BHO_MOVE_IIF_OO((bit, t, f))
#define BHO_MOVE_IIF_OO(par) BHO_MOVE_IIF_I ## par
#define BHO_MOVE_IIF_I(bit, t, f) BHO_MOVE_IIF_II(BHO_MOVE_IIF_ ## bit(t, f))
#define BHO_MOVE_IIF_II(id) id
#define BHO_MOVE_IIF_0(t, f) f
#define BHO_MOVE_IIF_1(t, f) t
*/

//BHO_MOVE_COLON
#define BHO_MOVE_COLON0
#define BHO_MOVE_COLON1 :
#define BHO_MOVE_COLON2 BHO_MOVE_COLON1
#define BHO_MOVE_COLON3 BHO_MOVE_COLON1
#define BHO_MOVE_COLON4 BHO_MOVE_COLON1
#define BHO_MOVE_COLON5 BHO_MOVE_COLON1
#define BHO_MOVE_COLON6 BHO_MOVE_COLON1
#define BHO_MOVE_COLON7 BHO_MOVE_COLON1
#define BHO_MOVE_COLON8 BHO_MOVE_COLON1
#define BHO_MOVE_COLON9 BHO_MOVE_COLON1

//BHO_MOVE_BITOR
#define BHO_MOVE_BITOR(x,y)    BHO_MOVE_BITOR_I(x,y)
#define BHO_MOVE_BITOR_I(x,y)  BHO_MOVE_BITOR##x##y
#define BHO_MOVE_BITOR00 0
#define BHO_MOVE_BITOR01 1
#define BHO_MOVE_BITOR10 1
#define BHO_MOVE_BITOR11 1

//BHO_MOVE_OR
#define BHO_MOVE_OR(x, y) BHO_MOVE_OR_I(x, y)
#define BHO_MOVE_OR_I(x, y) BHO_MOVE_BITOR(BHO_MOVE_BOOL(x), BHO_MOVE_BOOL(y))

//BHO_MOVE_BITAND
#define BHO_MOVE_BITAND(x,y)    BHO_MOVE_BITAND_I(x,y)
#define BHO_MOVE_BITAND_I(x,y)  BHO_MOVE_BITAND##x##y
#define BHO_MOVE_BITAND00 0
#define BHO_MOVE_BITAND01 0
#define BHO_MOVE_BITAND10 0
#define BHO_MOVE_BITAND11 1

//BHO_MOVE_AND
#define BHO_MOVE_AND(x, y) BHO_MOVE_AND_I(x, y)
#define BHO_MOVE_AND_I(x, y) BHO_MOVE_BITAND(BHO_MOVE_BOOL(x), BHO_MOVE_BOOL(y))

//BHO_MOVE_DEC
#define BHO_MOVE_DEC(x) BHO_MOVE_DEC_I(x)
#define BHO_MOVE_DEC_I(x) BHO_MOVE_DEC##x
#define BHO_MOVE_DEC1  0
#define BHO_MOVE_DEC2  1
#define BHO_MOVE_DEC3  2
#define BHO_MOVE_DEC4  3
#define BHO_MOVE_DEC5  4
#define BHO_MOVE_DEC6  5
#define BHO_MOVE_DEC7  6
#define BHO_MOVE_DEC8  7
#define BHO_MOVE_DEC9  8
#define BHO_MOVE_DEC10 9
#define BHO_MOVE_DEC11 10
#define BHO_MOVE_DEC12 11
#define BHO_MOVE_DEC13 12
#define BHO_MOVE_DEC14 13

//BHO_MOVE_SUB
#define BHO_MOVE_SUB(x, y) BHO_MOVE_SUB_I(x,y)
#define BHO_MOVE_SUB_I(x, y) BHO_MOVE_SUB##y(x)
#define BHO_MOVE_SUB0(x) x
#define BHO_MOVE_SUB1(x) BHO_MOVE_DEC(x)
#define BHO_MOVE_SUB2(x) BHO_MOVE_SUB1(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB3(x) BHO_MOVE_SUB2(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB4(x) BHO_MOVE_SUB3(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB5(x) BHO_MOVE_SUB4(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB6(x) BHO_MOVE_SUB5(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB7(x) BHO_MOVE_SUB6(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB8(x) BHO_MOVE_SUB7(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB9(x) BHO_MOVE_SUB8(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB10(x) BHO_MOVE_SUB9(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB11(x) BHO_MOVE_SUB10(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB12(x) BHO_MOVE_SUB11(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB13(x) BHO_MOVE_SUB12(BHO_MOVE_DEC(x))
#define BHO_MOVE_SUB14(x) BHO_MOVE_SUB13(BHO_MOVE_DEC(x))

//BHO_MOVE_INC
#define BHO_MOVE_INC(x) BHO_MOVE_INC_I(x)
#define BHO_MOVE_INC_I(x) BHO_MOVE_INC##x
#define BHO_MOVE_INC0  1
#define BHO_MOVE_INC1  2
#define BHO_MOVE_INC2  3
#define BHO_MOVE_INC3  4
#define BHO_MOVE_INC4  5
#define BHO_MOVE_INC5  6
#define BHO_MOVE_INC6  7
#define BHO_MOVE_INC7  8
#define BHO_MOVE_INC8  9
#define BHO_MOVE_INC9  10
#define BHO_MOVE_INC10 11
#define BHO_MOVE_INC11 12
#define BHO_MOVE_INC12 13
#define BHO_MOVE_INC13 14

//BHO_MOVE_ADD
#define BHO_MOVE_ADD(x, y) BHO_MOVE_ADD_I(x,y)
#define BHO_MOVE_ADD_I(x, y) BHO_MOVE_ADD##y(x)
#define BHO_MOVE_ADD0(x) x
#define BHO_MOVE_ADD1(x) BHO_MOVE_INC(x)
#define BHO_MOVE_ADD2(x) BHO_MOVE_ADD1(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD3(x) BHO_MOVE_ADD2(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD4(x) BHO_MOVE_ADD3(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD5(x) BHO_MOVE_ADD4(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD6(x) BHO_MOVE_ADD5(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD7(x) BHO_MOVE_ADD6(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD8(x) BHO_MOVE_ADD7(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD9(x) BHO_MOVE_ADD8(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD10(x) BHO_MOVE_ADD9(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD11(x) BHO_MOVE_ADD10(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD12(x) BHO_MOVE_ADD11(BHO_MOVE_INC(x))
#define BHO_MOVE_ADD13(x) BHO_MOVE_ADD12(BHO_MOVE_INC(x))

//BHO_MOVE_ITERATE_2TON
#define BHO_MOVE_ITERATE_2TO2(MACROFUNC)                                       MACROFUNC(2)
#define BHO_MOVE_ITERATE_2TO3(MACROFUNC)   BHO_MOVE_ITERATE_2TO2(MACROFUNC)  MACROFUNC(3)
#define BHO_MOVE_ITERATE_2TO4(MACROFUNC)   BHO_MOVE_ITERATE_2TO3(MACROFUNC)  MACROFUNC(4)
#define BHO_MOVE_ITERATE_2TO5(MACROFUNC)   BHO_MOVE_ITERATE_2TO4(MACROFUNC)  MACROFUNC(5)
#define BHO_MOVE_ITERATE_2TO6(MACROFUNC)   BHO_MOVE_ITERATE_2TO5(MACROFUNC)  MACROFUNC(6)
#define BHO_MOVE_ITERATE_2TO7(MACROFUNC)   BHO_MOVE_ITERATE_2TO6(MACROFUNC)  MACROFUNC(7)
#define BHO_MOVE_ITERATE_2TO8(MACROFUNC)   BHO_MOVE_ITERATE_2TO7(MACROFUNC)  MACROFUNC(8)
#define BHO_MOVE_ITERATE_2TO9(MACROFUNC)   BHO_MOVE_ITERATE_2TO8(MACROFUNC)  MACROFUNC(9)

//BHO_MOVE_ITERATE_1TON
#define BHO_MOVE_ITERATE_1TO1(MACROFUNC)                                       MACROFUNC(1)
#define BHO_MOVE_ITERATE_1TO2(MACROFUNC)   BHO_MOVE_ITERATE_1TO1(MACROFUNC)  MACROFUNC(2)
#define BHO_MOVE_ITERATE_1TO3(MACROFUNC)   BHO_MOVE_ITERATE_1TO2(MACROFUNC)  MACROFUNC(3)
#define BHO_MOVE_ITERATE_1TO4(MACROFUNC)   BHO_MOVE_ITERATE_1TO3(MACROFUNC)  MACROFUNC(4)
#define BHO_MOVE_ITERATE_1TO5(MACROFUNC)   BHO_MOVE_ITERATE_1TO4(MACROFUNC)  MACROFUNC(5)
#define BHO_MOVE_ITERATE_1TO6(MACROFUNC)   BHO_MOVE_ITERATE_1TO5(MACROFUNC)  MACROFUNC(6)
#define BHO_MOVE_ITERATE_1TO7(MACROFUNC)   BHO_MOVE_ITERATE_1TO6(MACROFUNC)  MACROFUNC(7)
#define BHO_MOVE_ITERATE_1TO8(MACROFUNC)   BHO_MOVE_ITERATE_1TO7(MACROFUNC)  MACROFUNC(8)
#define BHO_MOVE_ITERATE_1TO9(MACROFUNC)   BHO_MOVE_ITERATE_1TO8(MACROFUNC)  MACROFUNC(9)

//BHO_MOVE_ITERATE_0TON
#define BHO_MOVE_ITERATE_0TO0(MACROFUNC)                                       MACROFUNC(0)
#define BHO_MOVE_ITERATE_0TO1(MACROFUNC)   BHO_MOVE_ITERATE_0TO0(MACROFUNC)  MACROFUNC(1)
#define BHO_MOVE_ITERATE_0TO2(MACROFUNC)   BHO_MOVE_ITERATE_0TO1(MACROFUNC)  MACROFUNC(2)
#define BHO_MOVE_ITERATE_0TO3(MACROFUNC)   BHO_MOVE_ITERATE_0TO2(MACROFUNC)  MACROFUNC(3)
#define BHO_MOVE_ITERATE_0TO4(MACROFUNC)   BHO_MOVE_ITERATE_0TO3(MACROFUNC)  MACROFUNC(4)
#define BHO_MOVE_ITERATE_0TO5(MACROFUNC)   BHO_MOVE_ITERATE_0TO4(MACROFUNC)  MACROFUNC(5)
#define BHO_MOVE_ITERATE_0TO6(MACROFUNC)   BHO_MOVE_ITERATE_0TO5(MACROFUNC)  MACROFUNC(6)
#define BHO_MOVE_ITERATE_0TO7(MACROFUNC)   BHO_MOVE_ITERATE_0TO6(MACROFUNC)  MACROFUNC(7)
#define BHO_MOVE_ITERATE_0TO8(MACROFUNC)   BHO_MOVE_ITERATE_0TO7(MACROFUNC)  MACROFUNC(8)
#define BHO_MOVE_ITERATE_0TO9(MACROFUNC)   BHO_MOVE_ITERATE_0TO8(MACROFUNC)  MACROFUNC(9)

//BHO_MOVE_ITERATE_NTON
#define BHO_MOVE_ITERATE_1TO1(MACROFUNC)   MACROFUNC(1)
#define BHO_MOVE_ITERATE_2TO2(MACROFUNC)   MACROFUNC(2)
#define BHO_MOVE_ITERATE_3TO3(MACROFUNC)   MACROFUNC(3)
#define BHO_MOVE_ITERATE_4TO4(MACROFUNC)   MACROFUNC(4)
#define BHO_MOVE_ITERATE_5TO5(MACROFUNC)   MACROFUNC(5)
#define BHO_MOVE_ITERATE_6TO6(MACROFUNC)   MACROFUNC(6)
#define BHO_MOVE_ITERATE_7TO7(MACROFUNC)   MACROFUNC(7)
#define BHO_MOVE_ITERATE_8TO8(MACROFUNC)   MACROFUNC(8)
#define BHO_MOVE_ITERATE_9TO9(MACROFUNC)   MACROFUNC(9)

//BHO_MOVE_ITER2D_0TOMAX
#define BHO_MOVE_ITER2DLOW_0TOMAX0(MACROFUNC2D, M)                                                  MACROFUNC2D(M, 0)
#define BHO_MOVE_ITER2DLOW_0TOMAX1(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX0(MACROFUNC2D, M) MACROFUNC2D(M, 1)
#define BHO_MOVE_ITER2DLOW_0TOMAX2(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX1(MACROFUNC2D, M) MACROFUNC2D(M, 2)
#define BHO_MOVE_ITER2DLOW_0TOMAX3(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX2(MACROFUNC2D, M) MACROFUNC2D(M, 3)
#define BHO_MOVE_ITER2DLOW_0TOMAX4(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX3(MACROFUNC2D, M) MACROFUNC2D(M, 4)
#define BHO_MOVE_ITER2DLOW_0TOMAX5(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX4(MACROFUNC2D, M) MACROFUNC2D(M, 5)
#define BHO_MOVE_ITER2DLOW_0TOMAX6(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX5(MACROFUNC2D, M) MACROFUNC2D(M, 6)
#define BHO_MOVE_ITER2DLOW_0TOMAX7(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX6(MACROFUNC2D, M) MACROFUNC2D(M, 7)
#define BHO_MOVE_ITER2DLOW_0TOMAX8(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX7(MACROFUNC2D, M) MACROFUNC2D(M, 8)
#define BHO_MOVE_ITER2DLOW_0TOMAX9(MACROFUNC2D, M)  BHO_MOVE_ITER2DLOW_0TOMAX8(MACROFUNC2D, M) MACROFUNC2D(M, 9)

#define BHO_MOVE_ITER2D_0TOMAX0(MAX, MACROFUNC2D)                                                   BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 0)
#define BHO_MOVE_ITER2D_0TOMAX1(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX0(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 1)
#define BHO_MOVE_ITER2D_0TOMAX2(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX1(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 2)
#define BHO_MOVE_ITER2D_0TOMAX3(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX2(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 3)
#define BHO_MOVE_ITER2D_0TOMAX4(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX3(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 4)
#define BHO_MOVE_ITER2D_0TOMAX5(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX4(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 5)
#define BHO_MOVE_ITER2D_0TOMAX6(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX5(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 6)
#define BHO_MOVE_ITER2D_0TOMAX7(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX6(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 7)
#define BHO_MOVE_ITER2D_0TOMAX8(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX7(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 8)
#define BHO_MOVE_ITER2D_0TOMAX9(MAX, MACROFUNC2D)   BHO_MOVE_ITER2D_0TOMAX8(MAX, MACROFUNC2D)  BHO_MOVE_ITER2DLOW_0TOMAX##MAX(MACROFUNC2D, 9)

#define BHO_MOVE_ITER2D_0TOMAX(MAX, MACROFUNC2D)    BHO_MOVE_ITER2D_0TOMAX_I   (MAX, MACROFUNC2D)
#define BHO_MOVE_ITER2D_0TOMAX_I(MAX, MACROFUNC2D)  BHO_MOVE_ITER2D_0TOMAX##MAX(MAX, MACROFUNC2D)




//BHO_MOVE_CAT
#define BHO_MOVE_CAT(a, b) BHO_MOVE_CAT_I(a, b)
#define BHO_MOVE_CAT_I(a, b) a ## b
//#    define BHO_MOVE_CAT_I(a, b) BHO_MOVE_CAT_II(~, a ## b)
//#    define BHO_MOVE_CAT_II(p, res) res

#endif //#ifndef BHO_MOVE_DETAIL_FWD_MACROS_HPP
